// MST AlgoQuant — Shared Language System
// All translations in one place

const MST_I18N = {
  en: {
    // NAV
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.shop": "Shop",
    "nav.about": "About",
    "nav.contact": "Contact",

    // HERO
    "hero.label": "// MQL4 · MQL5 · MetaTrader Development",
    "hero.line1": "Algorithmic",
    "hero.line2": "Trading",
    "hero.line3": "Systems.",
    "hero.sub": "Custom Expert Advisors, indicators and trading strategies — built with precision for MetaTrader 4 & 5.",
    "hero.cta1": "Get a Quote",
    "hero.cta2": "View Services",

    // SERVICES
    "services.label": "// What I Build",
    "services.title": "Services",
    "s1.title": "Expert Advisor (EA)",
    "s1.desc": "Fully automated trading bots for MT4/MT5. Custom entry/exit logic, risk management, position sizing and multi-pair support.",
    "s2.title": "Custom Indicators",
    "s2.desc": "Bespoke technical indicators tailored to your strategy. Oscillators, overlays, signal alerts and dashboard panels.",
    "s3.title": "Strategy Consulting",
    "s3.desc": "Turn your trading idea into a backtested, optimized algorithm. From concept to code — with full documentation.",

    // ABOUT
    "about.label": "// About",
    "about.title": "MST AlgoQuant",
    "about.p1": "I am an independent MQL developer specializing in algorithmic trading systems for MetaTrader platforms. Every project is built from scratch, clean and well-documented.",
    "about.p2": "Whether you have a complete strategy or just an idea — I translate it into reliable, tested code that works in live markets.",
    "stat1": "Platform Support", "stat2": "Platform Support", "stat3": "Languages", "stat4": "Custom Code",

    // CONTACT
    "contact.label": "// Get In Touch",
    "contact.title": "Let's Work Together",
    "contact.desc": "Have a project in mind? Use the form below or reach out on social media.",
    "contact.soon": "Coming soon",
    "contact.writeUs": "Write to us",
    "form.name": "Your Name", "form.email": "Your Email", "form.subject": "Subject",
    "form.select": "Select a service...", "form.other": "Other", "form.message": "Message",
    "form.send": "Send Message", "form.sending": "Sending...",
    "form.ok": "✓ Message sent! I'll get back to you soon.",
    "form.err": "Something went wrong. Please try again.",

    // PORTFOLIO
    "portfolio.label": "// Past Work",
    "portfolio.title": "Portfolio",
    "portfolio.sub": "A selection of MQL4/MQL5 projects — indicators, Expert Advisors and trading tools developed at MST AlgoQuant.",
    "portfolio.teaser": "Custom MQL4/MQL5 indicators, Expert Advisors and trading tools — browse our completed projects.",
    "portfolio.btn": "View Portfolio →",
    "port.tag1": "Indicator",
    "port.desc1": "Multi-indicator dashboard panel showing RSI, MA Trend and ATR volatility in a single overlay. Works on all timeframes.",
    "port.more": "More projects coming soon...",
    "port.cta.title": "Have a Project in Mind?",
    "port.cta.desc": "Let's build your custom trading system from scratch.",
    "port.cta.btn": "Get a Quote →",

    // SHOP
    "shop.label": "// Ready to Use",
    "shop.title": "Free Downloads",
    "shop.sub": "Free and premium MQL4/MQL5 indicators and tools for MetaTrader 4 & 5 by MST AlgoQuant.",
    "shop.teaser": "Ready-to-use indicators and tools for MetaTrader — free to download, built from scratch.",
    "shop.btn": "Visit Shop →",
    "shop.free": "FREE",
    "shop.filter.all": "All",
    "shop.filter.ind": "Indicators",
    "shop.filter.ea": "Expert Advisors",
    "shop.filter.free": "Free",
    "shop.view": "View Details →",
    "shop.soon1": "New indicator coming soon...",
    "shop.soon2": "Expert Advisor coming soon...",

    // DASHBOARD PRODUCT PAGE
    "dash.badge": "FREE INDICATOR",
    "dash.title": "MST Dashboard v1.0",
    "dash.sub": "A clean, real-time multi-indicator dashboard for MetaTrader 4 & 5. RSI + Moving Average trend + ATR volatility — all in one panel with a combined signal score.",
    "dash.price.label": "Price",
    "dash.price.val": "FREE",
    "dash.platform.label": "Platform",
    "dash.platform.val": "MT4 + MT5",
    "dash.lang.label": "Language",
    "dash.lang.val": "MQL4 / MQL5",
    "dash.ver.label": "Version",
    "dash.ver.val": "1.0",
    "dash.download": "📥 Request Free Download",
    "dash.ask": "Ask a Question",
    "dash.features.label": "// What's Inside",
    "dash.features.title": "Features",
    "dash.f1.tag": "// RSI MODULE",
    "dash.f1.title": "RSI Overbought / Oversold",
    "dash.f1.desc": "Displays the current RSI value with color-coded feedback. Green when oversold (potential buy), red when overbought (potential sell). Configurable levels (default 70/30).",
    "dash.f2.tag": "// MA MODULE",
    "dash.f2.title": "Moving Average Trend",
    "dash.f2.desc": "Compares Fast EMA vs Slow EMA and current price position. Outputs: Strong Bull, Bullish, Bearish, Strong Bear or Ranging — always with clear color coding.",
    "dash.f3.tag": "// ATR MODULE",
    "dash.f3.title": "ATR Volatility Reading",
    "dash.f3.desc": "Shows the current Average True Range value so you can gauge market volatility at a glance. Useful for position sizing and stop-loss placement.",
    "dash.f4.tag": "// SIGNAL MODULE",
    "dash.f4.title": "Combined BUY / SELL Score",
    "dash.f4.desc": "Aggregates all signals into a single score. When RSI, MA trend and price action align — the panel shows a clear BUY or SELL signal. No signal when mixed.",
    "dash.how.label": "// Setup Guide",
    "dash.how.title": "How to Install",
    "dash.s1.title": "Request the File",
    "dash.s1.desc": "Click 'Request Free Download' and send us a quick email. We'll reply with the .mq4 or .mq5 source file within 24 hours.",
    "dash.s2.title": "Compile in MetaEditor",
    "dash.s2.desc": "Open the file in MetaEditor (F4 in MT4/MT5), press Compile (F7). The indicator will appear in your Navigator panel automatically.",
    "dash.s3.title": "Drag to Chart",
    "dash.s3.desc": "Drag the MST Dashboard from Navigator to any chart. Customize RSI period, MA periods and colors in the input settings. Done!",
    "dash.specs.label": "// Technical Details",
    "dash.specs.title": "Specifications",
    "dash.cta.title": "Get MST Dashboard for Free",
    "dash.cta.desc": "Send us a quick email and we'll reply with the source file for MT4 and/or MT5. No registration required.",
    "nav.back": "← Back to Shop",
    "footer.copy": "© 2025 MST AlgoQuant. All rights reserved."
  },

  tr: {
    "nav.home": "Ana Sayfa",
    "nav.services": "Hizmetler",
    "nav.portfolio": "Portfolio",
    "nav.shop": "İndir",
    "nav.about": "Hakkımda",
    "nav.contact": "İletişim",
    "hero.label": "// MQL4 · MQL5 · MetaTrader Geliştirme",
    "hero.line1": "Algoritmik",
    "hero.line2": "Ticaret",
    "hero.line3": "Sistemleri.",
    "hero.sub": "MetaTrader 4 ve 5 için özel Expert Advisor, indikatör ve ticaret stratejileri — hassasiyetle geliştirildi.",
    "hero.cta1": "Fiyat Al",
    "hero.cta2": "Hizmetleri Gör",
    "services.label": "// Ne Yapıyorum",
    "services.title": "Hizmetler",
    "s1.title": "Expert Advisor (EA)",
    "s1.desc": "MT4/MT5 için tamamen otomatik ticaret botları. Özel giriş/çıkış mantığı, risk yönetimi, pozisyon boyutlandırma ve çoklu parite desteği.",
    "s2.title": "Özel İndikatörler",
    "s2.desc": "Stratejinize özel teknik indikatörler. Osilatörler, overlay'ler, sinyal uyarıları ve panel göstergeleri.",
    "s3.title": "Strateji Danışmanlığı",
    "s3.desc": "Ticaret fikrinizi geriye dönük test edilmiş algoritmaya dönüştürün. Fikirden koda — tam dokümantasyon ile.",
    "about.label": "// Hakkımda",
    "about.title": "MST AlgoQuant",
    "about.p1": "MetaTrader platformları için algoritmik ticaret sistemleri konusunda uzmanlaşmış bağımsız bir MQL geliştiricisiyim.",
    "about.p2": "Eksiksiz bir stratejiniz ya da sadece bir fikriniz olsun — onu canlı piyasalarda çalışan güvenilir koda dönüştürüyorum.",
    "stat1": "Platform Desteği", "stat2": "Platform Desteği", "stat3": "Dil Desteği", "stat4": "Özel Kod",
    "contact.label": "// İletişime Geç",
    "contact.title": "Birlikte Çalışalım",
    "contact.desc": "Aklınızda bir proje mi var? Formu kullanın ya da sosyal medyadan ulaşın.",
    "contact.soon": "Yakında",
    "contact.writeUs": "Mesaj gönderin",
    "form.name": "Adınız", "form.email": "E-posta Adresiniz", "form.subject": "Konu",
    "form.select": "Hizmet seçin...", "form.other": "Diğer", "form.message": "Mesajınız",
    "form.send": "Mesaj Gönder", "form.sending": "Gönderiliyor...",
    "form.ok": "✓ Mesajınız iletildi! En kısa sürede dönüş yapacağım.",
    "form.err": "Bir hata oluştu. Lütfen tekrar deneyin.",
    "portfolio.label": "// Geçmiş Çalışmalar",
    "portfolio.title": "Portfolio",
    "portfolio.sub": "MST AlgoQuant tarafından geliştirilen MQL4/MQL5 projeleri — indikatörler, Expert Advisor'lar ve ticaret araçları.",
    "portfolio.teaser": "Özel MQL4/MQL5 indikatörleri ve ticaret araçları — tamamlanan projelerimize göz atın.",
    "portfolio.btn": "Portfolyoyu Gör →",
    "port.tag1": "İndikatör",
    "port.desc1": "RSI, MA Trendi ve ATR volatilitesini tek panelde gösteren çoklu indikatör dashboard'u.",
    "port.more": "Daha fazla proje yakında...",
    "port.cta.title": "Aklınızda Bir Proje mi Var?",
    "port.cta.desc": "Özel ticaret sisteminizi sıfırdan birlikte inşa edelim.",
    "port.cta.btn": "Fiyat Al →",
    "shop.label": "// Kullanıma Hazır",
    "shop.title": "Ücretsiz İndirmeler",
    "shop.sub": "MST AlgoQuant tarafından MetaTrader 4 ve 5 için hazırlanan ücretsiz indikatörler ve araçlar.",
    "shop.teaser": "MetaTrader için hazır indikatörler — ücretsiz indir, sıfırdan geliştirilmiş.",
    "shop.btn": "Mağazaya Git →",
    "shop.free": "ÜCRETSİZ",
    "shop.filter.all": "Tümü",
    "shop.filter.ind": "İndikatörler",
    "shop.filter.ea": "Expert Advisor",
    "shop.filter.free": "Ücretsiz",
    "shop.view": "Detayları Gör →",
    "shop.soon1": "Yeni indikatör yakında...",
    "shop.soon2": "Expert Advisor yakında...",
    "dash.badge": "ÜCRETSİZ İNDİKATÖR",
    "dash.title": "MST Dashboard v1.0",
    "dash.sub": "MetaTrader 4 ve 5 için temiz, gerçek zamanlı çoklu indikatör dashboard'u. RSI + Hareketli Ortalama trendi + ATR volatilitesi — kombine sinyal skoru ile tek panelde.",
    "dash.price.label": "Fiyat",
    "dash.price.val": "ÜCRETSİZ",
    "dash.platform.label": "Platform",
    "dash.platform.val": "MT4 + MT5",
    "dash.lang.label": "Dil",
    "dash.lang.val": "MQL4 / MQL5",
    "dash.ver.label": "Versiyon",
    "dash.ver.val": "1.0",
    "dash.download": "📥 Ücretsiz İndirme Talebi",
    "dash.ask": "Soru Sor",
    "dash.features.label": "// İçerik",
    "dash.features.title": "Özellikler",
    "dash.f1.tag": "// RSI MODÜLÜ",
    "dash.f1.title": "RSI Aşırı Alım / Satım",
    "dash.f1.desc": "Mevcut RSI değerini renk kodlu geri bildirimle gösterir. Aşırı satımda yeşil (potansiyel alım), aşırı alımda kırmızı. Varsayılan seviyeler 70/30, ayarlanabilir.",
    "dash.f2.tag": "// MA MODÜLÜ",
    "dash.f2.title": "Hareketli Ortalama Trendi",
    "dash.f2.desc": "Hızlı EMA ile Yavaş EMA'yı ve mevcut fiyat pozisyonunu karşılaştırır. Güçlü Yükseliş, Yükseliş, Düşüş, Güçlü Düşüş veya Yatay çıktısı verir.",
    "dash.f3.tag": "// ATR MODÜLÜ",
    "dash.f3.title": "ATR Volatilite Okuma",
    "dash.f3.desc": "Mevcut ATR değerini gösterir. Pozisyon boyutlandırma ve stop-loss yerleşimi için piyasa volatilitesini anlık takip edin.",
    "dash.f4.tag": "// SİNYAL MODÜLÜ",
    "dash.f4.title": "Kombine AL / SAT Skoru",
    "dash.f4.desc": "Tüm sinyalleri tek bir skorda toplar. RSI, MA trendi ve fiyat hareketi uyumlu olduğunda panel net AL veya SAT sinyali gösterir.",
    "dash.how.label": "// Kurulum",
    "dash.how.title": "Nasıl Kurulur",
    "dash.s1.title": "Dosyayı Talep Et",
    "dash.s1.desc": "Ücretsiz İndirme Talebi butonuna tıkla ve kısa bir mail gönder. 24 saat içinde .mq4 veya .mq5 kaynak dosyasını göndeririz.",
    "dash.s2.title": "MetaEditor'da Derle",
    "dash.s2.desc": "Dosyayı MetaEditor'da aç (MT4/MT5'te F4), Derle'ye bas (F7). İndikatör otomatik olarak Navigator panelinde görünür.",
    "dash.s3.title": "Grafiğe Sürükle",
    "dash.s3.desc": "MST Dashboard'u Navigator'dan herhangi bir grafiğe sürükle. Giriş ayarlarında RSI periyodu, MA periyotları ve renkleri özelleştir.",
    "dash.specs.label": "// Teknik Detaylar",
    "dash.specs.title": "Özellikler",
    "dash.cta.title": "MST Dashboard'u Ücretsiz Al",
    "dash.cta.desc": "Kısa bir mail gönder, MT4 ve/veya MT5 için kaynak dosyayı gönderelim. Kayıt gerekmez.",
    "nav.back": "← Mağazaya Dön",
    "footer.copy": "© 2025 MST AlgoQuant. Tüm hakları saklıdır."
  },

  nl: {
    "nav.home": "Home",
    "nav.services": "Diensten",
    "nav.portfolio": "Portfolio",
    "nav.shop": "Downloads",
    "nav.about": "Over",
    "nav.contact": "Contact",
    "hero.label": "// MQL4 · MQL5 · MetaTrader Ontwikkeling",
    "hero.line1": "Algo",
    "hero.line2": "Handels",
    "hero.line3": "Systemen.",
    "hero.sub": "Aangepaste Expert Advisors, indicatoren en handelsstrategieën — met precisie gebouwd voor MetaTrader 4 & 5.",
    "hero.cta1": "Offerte Aanvragen",
    "hero.cta2": "Bekijk Diensten",
    "services.label": "// Wat Ik Bouw",
    "services.title": "Diensten",
    "s1.title": "Expert Advisor (EA)",
    "s1.desc": "Volledig geautomatiseerde handelsbots voor MT4/MT5. Aangepaste logica, risicobeheer en multi-paar ondersteuning.",
    "s2.title": "Aangepaste Indicatoren",
    "s2.desc": "Op maat gemaakte indicatoren. Oscillatoren, overlays, signaalwaarschuwingen en dashboardpanelen.",
    "s3.title": "Strategie Consulting",
    "s3.desc": "Zet uw handelsidee om in een geoptimaliseerd algoritme. Van concept tot code — met volledige documentatie.",
    "about.label": "// Over",
    "about.title": "MST AlgoQuant",
    "about.p1": "Ik ben een onafhankelijke MQL-ontwikkelaar gespecialiseerd in algoritmische handelssystemen voor MetaTrader.",
    "about.p2": "Of u nu een complete strategie of alleen een idee heeft — ik vertaal het naar betrouwbare, geteste code.",
    "stat1": "Platform Ondersteuning", "stat2": "Platform Ondersteuning", "stat3": "Talen", "stat4": "Aangepaste Code",
    "contact.label": "// Neem Contact Op",
    "contact.title": "Laten We Samenwerken",
    "contact.desc": "Heeft u een project? Gebruik het formulier of neem contact op via sociale media.",
    "contact.soon": "Binnenkort",
    "contact.writeUs": "Stuur een bericht",
    "form.name": "Uw Naam", "form.email": "Uw E-mail", "form.subject": "Onderwerp",
    "form.select": "Selecteer een dienst...", "form.other": "Anders", "form.message": "Bericht",
    "form.send": "Verstuur", "form.sending": "Verzenden...",
    "form.ok": "✓ Bericht verzonden! Ik neem snel contact op.",
    "form.err": "Er is iets misgegaan. Probeer opnieuw.",
    "portfolio.label": "// Eerder Werk",
    "portfolio.title": "Portfolio",
    "portfolio.sub": "Een selectie van MQL4/MQL5 projecten door MST AlgoQuant.",
    "portfolio.teaser": "Aangepaste MQL4/MQL5 indicatoren en tools — blader door onze voltooide projecten.",
    "portfolio.btn": "Bekijk Portfolio →",
    "port.tag1": "Indicator",
    "port.desc1": "Multi-indicator dashboard met RSI, MA Trend en ATR volatiliteit in één paneel.",
    "port.more": "Meer projecten binnenkort...",
    "port.cta.title": "Heeft U Een Project?",
    "port.cta.desc": "Laten we uw handelssysteem from scratch bouwen.",
    "port.cta.btn": "Offerte Aanvragen →",
    "shop.label": "// Klaar voor Gebruik",
    "shop.title": "Gratis Downloads",
    "shop.sub": "Gratis MQL4/MQL5 indicatoren voor MetaTrader 4 & 5 door MST AlgoQuant.",
    "shop.teaser": "Kant-en-klare indicatoren voor MetaTrader — gratis te downloaden.",
    "shop.btn": "Bezoek Winkel →",
    "shop.free": "GRATIS",
    "shop.filter.all": "Alles",
    "shop.filter.ind": "Indicatoren",
    "shop.filter.ea": "Expert Advisors",
    "shop.filter.free": "Gratis",
    "shop.view": "Bekijk Details →",
    "shop.soon1": "Nieuwe indicator binnenkort...",
    "shop.soon2": "Expert Advisor binnenkort...",
    "dash.badge": "GRATIS INDICATOR",
    "dash.title": "MST Dashboard v1.0",
    "dash.sub": "Een overzichtelijk, realtime multi-indicator dashboard voor MetaTrader 4 & 5.",
    "dash.price.label": "Prijs", "dash.price.val": "GRATIS",
    "dash.platform.label": "Platform", "dash.platform.val": "MT4 + MT5",
    "dash.lang.label": "Taal", "dash.lang.val": "MQL4 / MQL5",
    "dash.ver.label": "Versie", "dash.ver.val": "1.0",
    "dash.download": "📥 Gratis Download Aanvragen",
    "dash.ask": "Stel een Vraag",
    "dash.features.label": "// Inhoud", "dash.features.title": "Functies",
    "dash.f1.tag": "// RSI MODULE", "dash.f1.title": "RSI Overbought / Oversold",
    "dash.f1.desc": "Toont de huidige RSI-waarde met kleurgecodeerde feedback. Groen bij oververkoop, rood bij overkoop.",
    "dash.f2.tag": "// MA MODULE", "dash.f2.title": "Voortschrijdend Gemiddelde Trend",
    "dash.f2.desc": "Vergelijkt Snelle EMA vs Trage EMA en huidige prijspositie. Uitvoer: Sterke Stijging, Stijgend, Dalend, Sterke Daling of Zijwaarts.",
    "dash.f3.tag": "// ATR MODULE", "dash.f3.title": "ATR Volatiliteitslezing",
    "dash.f3.desc": "Toont de huidige ATR-waarde voor marktvolatiliteit in één oogopslag.",
    "dash.f4.tag": "// SIGNAAL MODULE", "dash.f4.title": "Gecombineerde KOOP/VERKOOP Score",
    "dash.f4.desc": "Combineert alle signalen in één score. Bij uitlijning toont het paneel een duidelijk KOOP- of VERKOOPSIGNAAL.",
    "dash.how.label": "// Installatiegids", "dash.how.title": "Hoe te Installeren",
    "dash.s1.title": "Vraag het Bestand Aan",
    "dash.s1.desc": "Klik op 'Gratis Download Aanvragen' en stuur ons een e-mail. We antwoorden binnen 24 uur met het bronbestand.",
    "dash.s2.title": "Compileer in MetaEditor",
    "dash.s2.desc": "Open het bestand in MetaEditor (F4 in MT4/MT5), druk op Compileren (F7).",
    "dash.s3.title": "Versleep naar Grafiek",
    "dash.s3.desc": "Sleep het MST Dashboard naar een grafiek. Pas RSI-periode, MA-perioden en kleuren aan.",
    "dash.specs.label": "// Technische Details", "dash.specs.title": "Specificaties",
    "dash.cta.title": "Krijg MST Dashboard Gratis",
    "dash.cta.desc": "Stuur ons een e-mail en we sturen het bronbestand voor MT4 en/of MT5. Geen registratie vereist.",
    "nav.back": "← Terug naar Winkel",
    "footer.copy": "© 2025 MST AlgoQuant. Alle rechten voorbehouden."
  },

  de: {
    "nav.home": "Startseite",
    "nav.services": "Leistungen",
    "nav.portfolio": "Portfolio",
    "nav.shop": "Downloads",
    "nav.about": "Über mich",
    "nav.contact": "Kontakt",
    "hero.label": "// MQL4 · MQL5 · MetaTrader Entwicklung",
    "hero.line1": "Algo",
    "hero.line2": "Trading",
    "hero.line3": "Systeme.",
    "hero.sub": "Maßgeschneiderte Expert Advisors, Indikatoren und Handelsstrategien — präzise für MetaTrader 4 & 5 entwickelt.",
    "hero.cta1": "Angebot Anfordern",
    "hero.cta2": "Leistungen Ansehen",
    "services.label": "// Was Ich Entwickle",
    "services.title": "Leistungen",
    "s1.title": "Expert Advisor (EA)",
    "s1.desc": "Vollautomatische Handelsbots für MT4/MT5. Benutzerdefinierte Logik, Risikomanagement und Multi-Paar-Unterstützung.",
    "s2.title": "Benutzerdefinierte Indikatoren",
    "s2.desc": "Maßgeschneiderte Indikatoren. Oszillatoren, Overlays, Signalbenachrichtigungen und Panels.",
    "s3.title": "Strategie-Beratung",
    "s3.desc": "Verwandeln Sie Ihre Handelsidee in einen backtesteten Algorithmus. Vom Konzept bis zum Code.",
    "about.label": "// Über Mich",
    "about.title": "MST AlgoQuant",
    "about.p1": "Ich bin ein unabhängiger MQL-Entwickler spezialisiert auf algorithmische Handelssysteme für MetaTrader.",
    "about.p2": "Ob vollständige Strategie oder nur eine Idee — ich übersetze sie in zuverlässigen, getesteten Code.",
    "stat1": "Plattform-Support", "stat2": "Plattform-Support", "stat3": "Sprachen", "stat4": "Eigener Code",
    "contact.label": "// Kontakt",
    "contact.title": "Zusammenarbeiten",
    "contact.desc": "Haben Sie ein Projekt? Nutzen Sie das Formular oder kontaktieren Sie mich über Social Media.",
    "contact.soon": "Demnächst",
    "contact.writeUs": "Nachricht senden",
    "form.name": "Ihr Name", "form.email": "Ihre E-Mail", "form.subject": "Betreff",
    "form.select": "Leistung auswählen...", "form.other": "Sonstiges", "form.message": "Nachricht",
    "form.send": "Senden", "form.sending": "Wird gesendet...",
    "form.ok": "✓ Nachricht gesendet! Ich melde mich bald.",
    "form.err": "Fehler. Bitte erneut versuchen.",
    "portfolio.label": "// Frühere Arbeiten",
    "portfolio.title": "Portfolio",
    "portfolio.sub": "Eine Auswahl von MQL4/MQL5-Projekten von MST AlgoQuant.",
    "portfolio.teaser": "Individuelle MQL4/MQL5 Indikatoren und Tools — durchsuchen Sie unsere Projekte.",
    "portfolio.btn": "Portfolio ansehen →",
    "port.tag1": "Indikator",
    "port.desc1": "Multi-Indikator Dashboard mit RSI, MA-Trend und ATR-Volatilität in einem Panel.",
    "port.more": "Weitere Projekte folgen...",
    "port.cta.title": "Haben Sie Ein Projekt?",
    "port.cta.desc": "Lassen Sie uns Ihr individuelles Handelssystem von Grund auf entwickeln.",
    "port.cta.btn": "Angebot Anfordern →",
    "shop.label": "// Sofort Einsetzbar",
    "shop.title": "Kostenlose Downloads",
    "shop.sub": "Kostenlose MQL4/MQL5 Indikatoren für MetaTrader 4 & 5 von MST AlgoQuant.",
    "shop.teaser": "Sofort einsetzbare Indikatoren für MetaTrader — kostenlos herunterladen.",
    "shop.btn": "Shop besuchen →",
    "shop.free": "KOSTENLOS",
    "shop.filter.all": "Alle",
    "shop.filter.ind": "Indikatoren",
    "shop.filter.ea": "Expert Advisors",
    "shop.filter.free": "Kostenlos",
    "shop.view": "Details ansehen →",
    "shop.soon1": "Neuer Indikator bald verfügbar...",
    "shop.soon2": "Expert Advisor bald verfügbar...",
    "dash.badge": "KOSTENLOSER INDIKATOR",
    "dash.title": "MST Dashboard v1.0",
    "dash.sub": "Ein übersichtliches Echtzeit-Multi-Indikator-Dashboard für MetaTrader 4 & 5.",
    "dash.price.label": "Preis", "dash.price.val": "KOSTENLOS",
    "dash.platform.label": "Plattform", "dash.platform.val": "MT4 + MT5",
    "dash.lang.label": "Sprache", "dash.lang.val": "MQL4 / MQL5",
    "dash.ver.label": "Version", "dash.ver.val": "1.0",
    "dash.download": "📥 Kostenlosen Download Anfordern",
    "dash.ask": "Frage Stellen",
    "dash.features.label": "// Inhalt", "dash.features.title": "Funktionen",
    "dash.f1.tag": "// RSI MODUL", "dash.f1.title": "RSI Überkauft / Überverkauft",
    "dash.f1.desc": "Zeigt den aktuellen RSI-Wert mit farbcodiertem Feedback. Grün bei Überverkauf, rot bei Überkauf.",
    "dash.f2.tag": "// MA MODUL", "dash.f2.title": "Gleitender Durchschnitt Trend",
    "dash.f2.desc": "Vergleicht schnellen EMA mit langsamem EMA. Ausgabe: Starker Aufwärtstrend, Aufwärtstrend, Abwärtstrend oder Seitwärtsbewegung.",
    "dash.f3.tag": "// ATR MODUL", "dash.f3.title": "ATR Volatilitätslesung",
    "dash.f3.desc": "Zeigt den aktuellen ATR-Wert für Marktvolatilität auf einen Blick.",
    "dash.f4.tag": "// SIGNAL MODUL", "dash.f4.title": "Kombinierter KAUF/VERKAUF Score",
    "dash.f4.desc": "Aggregiert alle Signale in einem Score. Bei Ausrichtung zeigt das Panel ein klares KAUF- oder VERKAUFSSIGNAL.",
    "dash.how.label": "// Installationsanleitung", "dash.how.title": "Installation",
    "dash.s1.title": "Datei Anfordern",
    "dash.s1.desc": "Klicken Sie auf 'Download Anfordern' und senden Sie uns eine E-Mail. Wir antworten innerhalb von 24 Stunden.",
    "dash.s2.title": "In MetaEditor Kompilieren",
    "dash.s2.desc": "Öffnen Sie die Datei in MetaEditor (F4 in MT4/MT5), drücken Sie Kompilieren (F7).",
    "dash.s3.title": "Auf Chart Ziehen",
    "dash.s3.desc": "Ziehen Sie das MST Dashboard auf ein Chart und passen Sie die Einstellungen an.",
    "dash.specs.label": "// Technische Details", "dash.specs.title": "Spezifikationen",
    "dash.cta.title": "MST Dashboard Kostenlos Erhalten",
    "dash.cta.desc": "Senden Sie uns eine E-Mail und wir schicken die Quelldatei für MT4 und/oder MT5. Keine Registrierung erforderlich.",
    "nav.back": "← Zurück zum Shop",
    "footer.copy": "© 2025 MST AlgoQuant. Alle Rechte vorbehalten."
  },

  fr: {
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.shop": "Télécharger",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "hero.label": "// MQL4 · MQL5 · Développement MetaTrader",
    "hero.line1": "Trading",
    "hero.line2": "Algo",
    "hero.line3": "Systèmes.",
    "hero.sub": "Expert Advisors, indicateurs et stratégies sur mesure — développés avec précision pour MetaTrader 4 & 5.",
    "hero.cta1": "Demander un Devis",
    "hero.cta2": "Voir les Services",
    "services.label": "// Ce Que Je Développe",
    "services.title": "Services",
    "s1.title": "Expert Advisor (EA)",
    "s1.desc": "Robots de trading entièrement automatisés pour MT4/MT5. Logique personnalisée, gestion des risques et support multi-paires.",
    "s2.title": "Indicateurs Personnalisés",
    "s2.desc": "Indicateurs sur mesure. Oscillateurs, overlays, alertes et panneaux de tableau de bord.",
    "s3.title": "Conseil en Stratégie",
    "s3.desc": "Transformez votre idée en algorithme optimisé. Du concept au code — avec documentation.",
    "about.label": "// À Propos",
    "about.title": "MST AlgoQuant",
    "about.p1": "Je suis un développeur MQL indépendant spécialisé dans les systèmes de trading algorithmique pour MetaTrader.",
    "about.p2": "Stratégie complète ou simple idée — je la traduis en code fiable qui fonctionne sur les marchés réels.",
    "stat1": "Support Plateforme", "stat2": "Support Plateforme", "stat3": "Langues", "stat4": "Code Personnalisé",
    "contact.label": "// Contact",
    "contact.title": "Travaillons Ensemble",
    "contact.desc": "Un projet en tête ? Utilisez le formulaire ou contactez-moi sur les réseaux sociaux.",
    "contact.soon": "Bientôt",
    "contact.writeUs": "Nous écrire",
    "form.name": "Votre Nom", "form.email": "Votre E-mail", "form.subject": "Sujet",
    "form.select": "Choisir un service...", "form.other": "Autre", "form.message": "Message",
    "form.send": "Envoyer", "form.sending": "Envoi...",
    "form.ok": "✓ Message envoyé ! Je vous répondrai bientôt.",
    "form.err": "Une erreur est survenue. Réessayez.",
    "portfolio.label": "// Travaux Réalisés",
    "portfolio.title": "Portfolio",
    "portfolio.sub": "Une sélection de projets MQL4/MQL5 développés par MST AlgoQuant.",
    "portfolio.teaser": "Indicateurs MQL4/MQL5 et outils de trading — parcourez nos projets réalisés.",
    "portfolio.btn": "Voir le Portfolio →",
    "port.tag1": "Indicateur",
    "port.desc1": "Tableau de bord multi-indicateurs affichant RSI, tendance MA et volatilité ATR en un seul panneau.",
    "port.more": "Plus de projets bientôt...",
    "port.cta.title": "Vous Avez Un Projet ?",
    "port.cta.desc": "Construisons votre système de trading personnalisé from scratch.",
    "port.cta.btn": "Demander un Devis →",
    "shop.label": "// Prêt à l'Emploi",
    "shop.title": "Téléchargements Gratuits",
    "shop.sub": "Indicateurs MQL4/MQL5 gratuits pour MetaTrader 4 & 5 par MST AlgoQuant.",
    "shop.teaser": "Indicateurs prêts à l'emploi pour MetaTrader — téléchargement gratuit.",
    "shop.btn": "Visiter la Boutique →",
    "shop.free": "GRATUIT",
    "shop.filter.all": "Tout",
    "shop.filter.ind": "Indicateurs",
    "shop.filter.ea": "Expert Advisors",
    "shop.filter.free": "Gratuit",
    "shop.view": "Voir les Détails →",
    "shop.soon1": "Nouvel indicateur bientôt...",
    "shop.soon2": "Expert Advisor bientôt...",
    "dash.badge": "INDICATEUR GRATUIT",
    "dash.title": "MST Dashboard v1.0",
    "dash.sub": "Un tableau de bord multi-indicateurs en temps réel pour MetaTrader 4 & 5.",
    "dash.price.label": "Prix", "dash.price.val": "GRATUIT",
    "dash.platform.label": "Plateforme", "dash.platform.val": "MT4 + MT5",
    "dash.lang.label": "Langage", "dash.lang.val": "MQL4 / MQL5",
    "dash.ver.label": "Version", "dash.ver.val": "1.0",
    "dash.download": "📥 Demander le Téléchargement Gratuit",
    "dash.ask": "Poser une Question",
    "dash.features.label": "// Contenu", "dash.features.title": "Fonctionnalités",
    "dash.f1.tag": "// MODULE RSI", "dash.f1.title": "RSI Surachat / Survente",
    "dash.f1.desc": "Affiche la valeur RSI actuelle avec un retour codé par couleur. Vert en survente, rouge en surachat.",
    "dash.f2.tag": "// MODULE MA", "dash.f2.title": "Tendance Moyenne Mobile",
    "dash.f2.desc": "Compare l'EMA rapide vs l'EMA lente. Sortie : Forte Hausse, Haussier, Baissier, Forte Baisse ou Lateral.",
    "dash.f3.tag": "// MODULE ATR", "dash.f3.title": "Lecture de Volatilité ATR",
    "dash.f3.desc": "Affiche la valeur ATR actuelle pour évaluer la volatilité du marché en un coup d'œil.",
    "dash.f4.tag": "// MODULE SIGNAL", "dash.f4.title": "Score ACHAT/VENTE Combiné",
    "dash.f4.desc": "Agrège tous les signaux en un score unique. Quand RSI, tendance MA et prix sont alignés — signal clair ACHAT ou VENTE.",
    "dash.how.label": "// Guide d'Installation", "dash.how.title": "Comment Installer",
    "dash.s1.title": "Demander le Fichier",
    "dash.s1.desc": "Cliquez sur 'Demander le Téléchargement' et envoyez-nous un e-mail. Nous répondrons sous 24h.",
    "dash.s2.title": "Compiler dans MetaEditor",
    "dash.s2.desc": "Ouvrez le fichier dans MetaEditor (F4 dans MT4/MT5), appuyez sur Compiler (F7).",
    "dash.s3.title": "Glisser sur le Graphique",
    "dash.s3.desc": "Glissez le MST Dashboard sur un graphique et personnalisez les paramètres.",
    "dash.specs.label": "// Détails Techniques", "dash.specs.title": "Spécifications",
    "dash.cta.title": "Obtenez MST Dashboard Gratuitement",
    "dash.cta.desc": "Envoyez-nous un e-mail et nous vous enverrons le fichier source pour MT4 et/ou MT5. Aucune inscription requise.",
    "nav.back": "← Retour à la Boutique",
    "footer.copy": "© 2025 MST AlgoQuant. Tous droits réservés."
  }
};

const MST_PAGE_TITLES = {
  en: { index: 'MST AlgoQuant — MQL4 & MQL5 Expert Advisor Developer', portfolio: 'Portfolio — MST AlgoQuant', shop: 'Shop — Free MQL4/MQL5 Indicators | MST AlgoQuant', dashboard: 'MST Dashboard v1.0 — Free MQL Indicator' },
  tr: { index: 'MST AlgoQuant — MQL4 & MQL5 Expert Advisor Geliştirici', portfolio: 'Portfolio — MST AlgoQuant', shop: 'İndirmeler — MST AlgoQuant', dashboard: 'MST Dashboard v1.0 — Ücretsiz MQL İndikatörü' },
  nl: { index: 'MST AlgoQuant — MQL4 & MQL5 Expert Advisor Ontwikkelaar', portfolio: 'Portfolio — MST AlgoQuant', shop: 'Downloads — MST AlgoQuant', dashboard: 'MST Dashboard v1.0 — Gratis MQL Indicator' },
  de: { index: 'MST AlgoQuant — MQL4 & MQL5 Expert Advisor Entwickler', portfolio: 'Portfolio — MST AlgoQuant', shop: 'Downloads — MST AlgoQuant', dashboard: 'MST Dashboard v1.0 — Kostenloser MQL Indikator' },
  fr: { index: 'MST AlgoQuant — Développeur Expert Advisor MQL4 & MQL5', portfolio: 'Portfolio — MST AlgoQuant', shop: 'Boutique — MST AlgoQuant', dashboard: 'MST Dashboard v1.0 — Indicateur MQL Gratuit' }
};

// ── CORE FUNCTIONS ──────────────────────────────────────────────
function mstDetectLang() {
  const saved = localStorage.getItem('mst_lang');
  if (saved && ['tr','en','nl','de','fr'].includes(saved)) return saved;
  const code = (navigator.language || 'en').slice(0,2).toLowerCase();
  return ['tr','en','nl','de','fr'].includes(code) ? code : 'en';
}

function mstApplyLang(lang, pageKey) {
  const dict = MST_I18N[lang] || MST_I18N.en;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const k = el.getAttribute('data-i18n');
    if (dict[k] !== undefined) el.textContent = dict[k];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const k = el.getAttribute('data-i18n-placeholder');
    if (dict[k] !== undefined) el.placeholder = dict[k];
  });
  document.querySelectorAll('[data-i18n-href]').forEach(el => {
    const k = el.getAttribute('data-i18n-href');
    if (dict[k] !== undefined) el.href = dict[k];
  });
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  document.documentElement.lang = lang;
  if (pageKey && MST_PAGE_TITLES[lang] && MST_PAGE_TITLES[lang][pageKey]) {
    document.title = MST_PAGE_TITLES[lang][pageKey];
  }
}

function mstInitLang(pageKey) {
  const lang = mstDetectLang();
  mstApplyLang(lang, pageKey);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const l = btn.dataset.lang;
      localStorage.setItem('mst_lang', l);
      mstApplyLang(l, pageKey);
    });
  });
}
